# Generated by Django 4.0.4 on 2022-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discountPercentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
